### ISSUE TITLE
pr2_gazebo's /kinect_head_c2/depth/image_raw is confusing.

### ISSUE THREAD

**Issue by aginika** [jsk-ros-pkg/jsk_robot#416]
![depth_confusion](https://cloud.githubusercontent.com/assets/3803922/9196721/02282caa-4069-11e5-8bc1-a7d174de88f9.gif)

Two type msg is confusing in this topic.

/head_mount_kinect/depth/image_raw is subscribed by /relay_c2_depth_image_raw.
And /relay_c2_depth_image_raw is publishing this msg.
/head_mount_kinect/depth/image_raw  is already confising, so the problem is publisher /gazebo.
```
rostopic echo /head_mount_kinect/depth/image_raw
---
header: 
  seq: 119
  stamp: 
    secs: 145
    nsecs: 421000000
  frame_id: head_mount_kinect_ir_optical_frame
height: 480
width: 640
encoding: 32FC1
is_bigendian: 0
step: 2560
---
header: 
  seq: 120
  stamp: 
    secs: 145
    nsecs: 421000000
  frame_id: head_mount_kinect_ir_optical_frame
height: 480
width: 640
encoding: mono8
is_bigendian: 0
step: 640
---
header: 
  seq: 121
  stamp: 
    secs: 145
    nsecs: 668000000
  frame_id: head_mount_kinect_rgb_optical_frame
height: 480
width: 640
encoding: 32FC1
is_bigendian: 0
step: 2560
---
header: 
  seq: 122
  stamp: 
    secs: 146
    nsecs: 421000000
  frame_id: head_mount_kinect_ir_optical_frame
height: 480
width: 640
encoding: 32FC1
is_bigendian: 0
step: 2560
---
header: 
  seq: 123
  stamp: 
    secs: 146
    nsecs: 421000000
  frame_id: head_mount_kinect_ir_optical_frame
height: 480
width: 640
encoding: mono8
is_bigendian: 0
step: 640

```
