### ISSUE TITLE
PepperのEuslispをつかった動かし方について

### ISSUE THREAD

**Issue by M-Onitsuka** [jsk-ros-pkg/jsk_robot#903]
Pepperを動かそうと考えています。
今のところ
[http://wiki.ros.org/pepper/Tutorials](url)
を参考に
```roslaunch pepper_bringup pepper_full_py.launch nao_ip:=<yourRobotIP> roscore_ip:=<roscore_ip>```
として
```
rostopic pub /cmd_vel geometry_msgs/Twist "linear:
  x: 0.0
  y: 0.0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: -0.2"
```
などとして動かしています。
Euslispなどからangle-vectorを送る方法はありますでしょうか。
また、上記launchが
```
================================================================================REQUIRED process [naoqi_joint_states-2] has died!
process has finished cleanly
log file: /home/m-onitsuka/.ros/log/d618a2ba-326f-11e8-8659-b808cf4bc648/naoqi_joint_states-2*.log
Initiating shutdown!
================================================================================
```
となって止まるのですが、原因がよくわかりません。
